spring.application.name=demo

spring.security.user.name=user
spring.security.user.password=lj0131

#mysql
# DB 연결 부분 추가
spring.datasource.url=JDBC:mysql://localhost:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
spring.datasource.username=demo_user
spring.datasource.password=lj0131
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
